### ISSUE TITLE
When a player dies from a fall, weird things happen

### ISSUE THREAD

**Issue by whathe12** [hexahedronic/arista#2]
After the 30 second respawn time, my player respawned but not in the normal respawn point and instead was half inside a wall and did not have any physgun or hands or tool gun out. I proceeded to noclip from my spot because I had spawned into the wall and then my camera view suddenly rose and my player began to move very slowly, almost gliding, still with not physgun/tool gun/hands able to use (The 1, 2, 3, 4 menu for entities was also not working).

**Comment by CaveeJohnson** [comment]
I'll test this later today and see if I can reproduce it.

**Comment by CaveeJohnson** [comment]
Cannot reproduce, if you want me to have a look then pm me when you see me on garry's mod and I'll join you and figure it out.

Also, what do you mean by the '1, 2, 3, 4 menu for entities'? Do you mean F1 for the main menu and F2 for the access menu and whatnot?

**Comment by CaveeJohnson** [comment]
https://github.com/hexahedronic/arista/commit/e3ebce0714b0eb07ec6d0a308a774adc061741f0
Issue was found to be caused by ULX, not going to fix because it's a bad addon anyway, use Evolve, AOWL or litteraly ANY OTHER admin mod.
