### ISSUE TITLE
Unownable command breaks doors

### ISSUE THREAD

**Issue by hiddencoders** [hexahedronic/arista#4]
Toggling 'unownable' status on a door will make it unownable, using the command with a single argument will name a door AND make it unownable, and if the argument is _'remove'_ it removes the unownable status. However, using _'remove'_ will set the ownership to TEAM_NONE, practically making the door once again unownable to anyone.

Issue: **No way to make doors ownable again.**

See plugins/doors/sv_init.lua:225

**Comment by CaveeJohnson** [comment]
Will fix when I get back later

**Comment by CaveeJohnson** [comment]
That was the longest piss I have ever taken
Fixed.
