### ISSUE TITLE
Fist rightclick

### ISSUE THREAD

**Issue by hiddencoders** [hexahedronic/arista#5]
The fists's rightclick has no punching function like the primary attack, making it look buggy. Although the previous functions are important, the swep should still use the secondary attack as a punch when it comes to NPC's or players. 

**Issue: Implement the same function of primary attacks on secondary attacks on the hand swep.
Issue2: NPCs can be picked up. Just. No.**

**Comment by CaveeJohnson** [comment]
https://github.com/hexahedronic/arista/commit/07961939063a6baff45961abb87b1f02827dc830
